export const courses = [
  {
    id: 1,
    title: "Learn App development in 30 days",
    enrolled: 500,
    stars: 4.0,
    price: 4000,
    skill: "app development",
    category: "languages",
    linkPath: require("./assets/course/Fingent-01-1024x555-1.png"),
  },
  {
    id: 2,
    title: "Learn Web development in 30 days",
    enrolled: 600,
    stars: 4.4,
    price: 5000,
    skill: "web development",
    category: "languages",
    linkPath: require("./assets/course/original-50f74222752e83994c76f20ed83d7c01.webp"),
  },
  {
    id: 3,
    title: "Learn Active voice passive voice",
    enrolled: 600,
    stars: 4.4,
    price: 5000,
    skill: "english",
    category: "english",
    linkPath: require("./assets/course/dess.webp"),
  },
  {
    id: 4,
    title: "Learn algebra in 50 days",
    enrolled: 600,
    stars: 4.2,
    price: 2000,
    skill: "math",
    category: "math",
    linkPath: require("./assets/course/ui-design-and-ux-design-1.png"),
  },
  {
    id: 5,
    title: "Learn brain of human",
    enrolled: 600,
    stars: 4.2,
    price: 2000,
    skill: "science",
    category: "science",
    linkPath: require("./assets/course/ui-design-and-ux-design-1.png"),
  },
  {
    id: 6,
    title: "Learn Python programming",
    enrolled: 450,
    stars: 4.5,
    price: 3500,
    skill: "programming",
    category: "languages",
    linkPath: require("./assets/course/dess.webp"),
  },
  {
    id: 7,
    title: "Master JavaScript",
    enrolled: 800,
    stars: 4.7,
    price: 6000,
    skill: "programming",
    category: "languages",
    linkPath: require("./assets/course/original-50f74222752e83994c76f20ed83d7c01.webp"),
  },
  {
    id: 8,
    title: "English Grammar Essentials",
    enrolled: 300,
    stars: 4.2,
    price: 3000,
    skill: "english",
    category: "english",
    linkPath: require("./assets/course/Fingent-01-1024x555-1.png"),
  },
  {
    id: 9,
    title: "Learn Calculus",
    enrolled: 350,
    stars: 4.1,
    price: 2500,
    skill: "math",
    category: "math",
    linkPath: require("./assets/course/ui-design-and-ux-design-1.png"),
  },
  {
    id: 10,
    title: "Introduction to Physics",
    enrolled: 400,
    stars: 4.3,
    price: 3000,
    skill: "science",
    category: "science",
    linkPath: require("./assets/course/original-50f74222752e83994c76f20ed83d7c01.webp"),
  },
  {
    id: 11,
    title: "iOS App Development",
    enrolled: 550,
    stars: 4.6,
    price: 4500,
    skill: "app development",
    category: "languages",
    linkPath: require("./assets/course/Fingent-01-1024x555-1.png"),
  },
  {
    id: 12,
    title: "Learn React.js",
    enrolled: 700,
    stars: 4.8,
    price: 5500,
    skill: "web development",
    category: "languages",
    linkPath: require("./assets/course/original-50f74222752e83994c76f20ed83d7c01.webp"),
  },
  {
    id: 13,
    title: "Business English Communication",
    enrolled: 200,
    stars: 4.0,
    price: 2800,
    skill: "english",
    category: "english",
    linkPath: require("./assets/course/Fingent-01-1024x555-1.png"),
  },
  {
    id: 14,
    title: "Linear Algebra Fundamentals",
    enrolled: 250,
    stars: 4.2,
    price: 2200,
    skill: "math",
    category: "math",
    linkPath: require("./assets/course/ui-design-and-ux-design-1.png"),
  },
  {
    id: 15,
    title: "Chemistry Basics",
    enrolled: 300,
    stars: 4.0,
    price: 2800,
    skill: "science",
    category: "science",
    linkPath: require("./assets/course/dess.webp"),
  },
  {
    id: 16,
    title: "Android App Development",
    enrolled: 500,
    stars: 4.4,
    price: 4500,
    skill: "app development",
    category: "languages",
    linkPath: require("./assets/course/original-50f74222752e83994c76f20ed83d7c01.webp"),
  },
  {
    id: 17,
    title: "Learn HTML and CSS",
    enrolled: 750,
    stars: 4.6,
    price: 5000,
    skill: "web development",
    category: "languages",
    linkPath: require("./assets/course/Fingent-01-1024x555-1.png"),
  },
  {
    id: 18,
    title: "IELTS Exam Preparation",
    enrolled: 400,
    stars: 4.3,
    price: 3200,
    skill: "english",
    category: "english",
    linkPath: require("./assets/course/ui-design-and-ux-design-1.png"),
  },
  {
    id: 19,
    title: "Probability and Statistics",
    enrolled: 350,
    stars: 4.2,
    price: 2400,
    skill: "math",
    category: "math",
    linkPath: require("./assets/course/dess.webp"),
  },
  {
    id: 20,
    title: "Biology Fundamentals",
    enrolled: 400,
    stars: 4.0,
    price: 2800,
    skill: "science",
    category: "science",
    linkPath: require("./assets/course/original-50f74222752e83994c76f20ed83d7c01.webp"),
  },
  {
    id: 21,
    title: "Swift Programming for Beginners",
    enrolled: 450,
    stars: 4.3,
    price: 3800,
    skill: "app development",
    category: "languages",
    linkPath: require("./assets/course/Fingent-01-1024x555-1.png"),
  },
  {
    id: 22,
    title: "Full Stack Web Development",
    enrolled: 900,
    stars: 4.8,
    price: 6500,
    skill: "web development",
    category: "languages",
    linkPath: require("./assets/course/ui-design-and-ux-design-1.png"),
  },
  {
    id: 23,
    title: "Advanced English Vocabulary",
    enrolled: 250,
    stars: 4.1,
    price: 3200,
    skill: "english",
    category: "english",
    linkPath: require("./assets/course/dess.webp"),
  },
  {
    id: 24,
    title: "Discrete Mathematics",
    enrolled: 300,
    stars: 4.0,
    price: 2500,
    skill: "math",
    category: "math",
    linkPath: require("./assets/course/original-50f74222752e83994c76f20ed83d7c01.webp"),
  },
  {
    id: 25,
    title: "Introduction to Astronomy",
    enrolled: 350,
    stars: 4.2,
    price: 2800,
    skill: "science",
    category: "science",
    linkPath: require("./assets/course/Fingent-01-1024x555-1.png"),
  },
  {
    id: 26,
    title: "Android Game Development",
    enrolled: 600,
    stars: 4.5,
    price: 4200,
    skill: "app development",
    category: "languages",
    linkPath: require("./assets/course/ui-design-and-ux-design-1.png"),
  },
  {
    id: 27,
    title: "Vue.js Essentials",
    enrolled: 800,
    stars: 4.7,
    price: 5500,
    skill: "web development",
    category: "languages",
    linkPath: require("./assets/course/dess.webp"),
  },
  {
    id: 28,
    title: "Business Writing Skills",
    enrolled: 200,
    stars: 3.9,
    price: 3000,
    skill: "english",
    category: "english",
    linkPath: require("./assets/course/original-50f74222752e83994c76f20ed83d7c01.webp"),
  },
  {
    id: 29,
    title: "Mathematical Modeling",
    enrolled: 300,
    stars: 4.0,
    price: 2800,
    skill: "math",
    category: "math",
    linkPath: require("./assets/course/Fingent-01-1024x555-1.png"),
  },
  {
    id: 30,
    title: "Chemical Reactions",
    enrolled: 400,
    stars: 4.1,
    price: 3200,
    skill: "science",
    category: "science",
    linkPath: require("./assets/course/ui-design-and-ux-design-1.png"),
  },
  {
    id: 31,
    title: "iOS App Development with Swift",
    enrolled: 550,
    stars: 4.6,
    price: 4500,
    skill: "app development",
    category: "languages",
    linkPath: require("./assets/course/dess.webp"),
  },
  {
    id: 32,
    title: "CSS Grid Layout",
    enrolled: 700,
    stars: 4.8,
    price: 5500,
    skill: "web development",
    category: "languages",
    linkPath: require("./assets/course/original-50f74222752e83994c76f20ed83d7c01.webp"),
  },
  {
    id: 33,
    title: "English Pronunciation Mastery",
    enrolled: 250,
    stars: 4.2,
    price: 3200,
    skill: "english",
    category: "english",
    linkPath: require("./assets/course/Fingent-01-1024x555-1.png"),
  },
  {
    id: 34,
    title: "Calculus II",
    enrolled: 300,
    stars: 4.0,
    price: 2500,
    skill: "math",
    category: "math",
    linkPath: require("./assets/course/Fingent-01-1024x555-1.png"),
  },
  {
    id: 35,
    title: "Introduction to Geology",
    enrolled: 350,
    stars: 4.2,
    price: 2800,
    skill: "science",
    category: "science",
    linkPath: require("./assets/course/ui-design-and-ux-design-1.png"),
  },
  {
    id: 36,
    title: "Mobile App Design",
    enrolled: 500,
    stars: 4.4,
    price: 4500,
    skill: "app development",
    category: "languages",
    linkPath: require("./assets/course/dess.webp"),
  },
  {
    id: 37,
    title: "Node.js Fundamentals",
    enrolled: 750,
    stars: 4.6,
    price: 5000,
    skill: "web development",
    category: "languages",
    linkPath: require("./assets/course/original-50f74222752e83994c76f20ed83d7c01.webp"),
  },
  {
    id: 38,
    title: "English for Business Meetings",
    enrolled: 400,
    stars: 4.3,
    price: 3200,
    skill: "english",
    category: "english",
    linkPath: require("./assets/course/Fingent-01-1024x555-1.png"),
  },
  {
    id: 39,
    title: "Abstract Algebra",
    enrolled: 350,
    stars: 4.2,
    price: 2400,
    skill: "math",
    category: "math",
    linkPath: require("./assets/course/ui-design-and-ux-design-1.png"),
  },
  {
    id: 40,
    title: "Environmental Science",
    enrolled: 400,
    stars: 4.0,
    price: 2800,
    skill: "science",
    category: "science",
    linkPath: require("./assets/course/dess.webp"),
  },
  {
    id: 41,
    title: "Flutter App Development",
    enrolled: 450,
    stars: 4.3,
    price: 3800,
    skill: "app development",
    category: "languages",
    linkPath: require("./assets/course/original-50f74222752e83994c76f20ed83d7c01.webp"),
  },
  {
    id: 42,
    title: "Responsive Web Design",
    enrolled: 900,
    stars: 4.8,
    price: 6500,
    skill: "web development",
    category: "languages",
    linkPath: require("./assets/course/Fingent-01-1024x555-1.png"),
  },
  {
    id: 43,
    title: "Business English Writing",
    enrolled: 250,
    stars: 4.1,
    price: 3200,
    skill: "english",
    category: "english",
    linkPath: require("./assets/course/ui-design-and-ux-design-1.png"),
  },
  {
    id: 44,
    title: "Statistics in R",
    enrolled: 300,
    stars: 4.0,
    price: 2500,
    skill: "math",
    category: "math",
    linkPath: require("./assets/course/dess.webp"),
  },
  {
    id: 45,
    title: "Astrophysics",
    enrolled: 350,
    stars: 4.2,
    price: 2800,
    skill: "science",
    category: "science",
    linkPath: require("./assets/course/original-50f74222752e83994c76f20ed83d7c01.webp"),
  },
  {
    id: 46,
    title: "SwiftUI Development",
    enrolled: 600,
    stars: 4.5,
    price: 4200,
    skill: "app development",
    category: "languages",
    linkPath: require("./assets/course/Fingent-01-1024x555-1.png"),
  },
  {
    id: 47,
    title: "MongoDB Essentials",
    enrolled: 800,
    stars: 4.7,
    price: 5500,
    skill: "web development",
    linkPath: require("./assets/course/original-50f74222752e83994c76f20ed83d7c01.webp"),
    category: "languages",
  },

  {
    id: 48,
    title: "Advanced English Grammar",
    enrolled: 200,
    stars: 3.9,
    price: 3000,
    skill: "english",
    category: "english",
    linkPath: require("./assets/course/Fingent-01-1024x555-1.png"),
  },
  {
    id: 49,
    title: "Mathematical Optimization",
    enrolled: 300,
    stars: 4.0,
    price: 2800,
    skill: "math",
    category: "math",
    linkPath: require("./assets/course/Fingent-01-1024x555-1.png"),
  },
  {
    id: 50,
    title: "Marine Biology",
    enrolled: 400,
    stars: 4.1,
    price: 3200,
    skill: "science",
    category: "science",
    linkPath: require("./assets/course/ui-design-and-ux-design-1.png"),
  },
];

export const clients = [
  {
    name: "John Doe",
    review:
      "The online courses provided by this platform are top-notch. I've learned so much and improved my skills significantly. Highly recommended!",
    stars: 5,
    linkPath: require("./assets/blank-profile-picture-973460_960_720.webp"),
  },
  {
    name: "Jane Smith",
    review:
      "I'm really impressed with the quality and depth of the MCQs offered on this website. They have helped me prepare for my exams effectively.",
    stars: 4,
    linkPath: require("./assets/blank-profile-picture-973460_960_720.webp"),
  },
  {
    name: "David Johnson",
    review:
      "The courses are well-structured and easy to follow. The interactive quizzes have been instrumental in reinforcing my understanding of the topics.",
    stars: 4.5,
    linkPath: require("./assets/blank-profile-picture-973460_960_720.webp"),
  },
  {
    name: "Sarah Thompson",
    review:
      "I'm extremely satisfied with the range of courses available on this platform. The content is comprehensive, and the instructors are knowledgeable.",
    stars: 4,
    linkPath: require("./assets/blank-profile-picture-973460_960_720.webp"),
  },
  {
    name: "Michael Anderson",
    review:
      "The MCQs provided here have been invaluable in testing my knowledge and preparing for certification exams. Great platform for self-assessment!",
    stars: 4.5,
    linkPath: require("./assets/blank-profile-picture-973460_960_720.webp"),
  },
  {
    name: "Emily Wilson",
    review:
      "I've thoroughly enjoyed the interactive nature of the courses. The ability to engage with instructors and fellow learners has enhanced my learning experience.",
    stars: 5,
    linkPath: require("./assets/blank-profile-picture-973460_960_720.webp"),
  },
  {
    name: "Alex Turner",
    review:
      "The courses have exceeded my expectations in terms of content quality and relevance. The knowledge gained here has been directly applicable to my job.",
    stars: 5,
    linkPath: require("./assets/blank-profile-picture-973460_960_720.webp"),
  },
  {
    name: "Olivia Davis",
    review:
      "The user-friendly interface and clear instructions make learning a breeze. The courses are well-organized and easy to navigate.",
    stars: 4,
    linkPath: require("./assets/blank-profile-picture-973460_960_720.webp"),
  },
  {
    name: "William Johnson",
    review:
      "I appreciate the flexibility of the online courses, allowing me to balance learning with my other commitments. The instructors are highly knowledgeable and responsive.",
    stars: 4.5,
    linkPath: require("./assets/blank-profile-picture-973460_960_720.webp"),
  },
  {
    name: "Sophia Adams",
    review:
      "The MCQs have been instrumental in helping me gauge my understanding and identify areas for improvement. They have greatly enhanced my exam preparation.",
    stars: 4,
    linkPath: require("./assets/blank-profile-picture-973460_960_720.webp"),
  },
  // Add more objects as needed
];

export const detailCourse = [
  {
    id: 1,
    subject: "math",
    class: "k",
    chapter: "linear algebra",
    lesson: "matrix",
    mcqsId: 423423,
    isPrivate: true,
  },
  {
    id: 2,
    category: "science",
    class: "1",
    chapter: "human brain",
    lesson: "structure of brain",
    mcqsId: 234323424,
    isPrivate: true,
  },
  {
    id: 3,
    category: "language arts",
    class: "2",
    chapter: "reading",
    lesson: "Reading Strategies",
    mcqsId: 332423423,
    isPrivate: true,
  },
  {
    id: 4,
    category: "social studies",
    class: "3",
    chapter: "culture",
    lesson: "CITIZENSHIP STANDARD",
    mcqsId: 634543,
    isPrivate: true,
  },
];

const mcqs = [
  {
    id: 1,
    question: "how many parts of brain",
    answer: "4",
    options: ["2", "4", "1", "3"],
    questionImage: "some",
    courseId: 3,
  },
];
